using HotelOS.SharedKernel.Abstractions;
using Reception.Domain.Enums;
using Reception.Domain.Events;
using Reception.Domain.ValueObjects;

namespace Reception.Domain.Entities;

/// <summary>
/// Aggregate Root: Room.
///
/// The Room is the most critical aggregate in HotelOS. All state transitions
/// are gated through methods on this class — no external code sets Status directly.
/// This is Encapsulation in action: the Room owns its own invariants.
///
/// CONCURRENCY DESIGN (ISO/IEC 27001 — data integrity under concurrent access):
/// RowVersion is a database-generated byte[] timestamp that EF Core reads back
/// after every save. If two requests load the same Room and both try to save,
/// the second save fails with DbUpdateConcurrencyException because the RowVersion
/// they read is now stale — EF Core detects the mismatch. This is our second line
/// of defence after the Redis distributed lock.
/// </summary>
public sealed class Room : AggregateRoot<Guid>
{
    // ── Persistent Properties ─────────────────────────────────────────────────

    public RoomNumber RoomNumber { get; private set; } = null!;
    public RoomType Type { get; private set; }
    public RoomStatus Status { get; private set; }
    public Money NightlyRate { get; private set; } = null!;
    public int Floor { get; private set; }

    /// <summary>
    /// Indicates whether this room is positioned near an elevator.
    /// Used as the final tiebreaker in the room assignment algorithm.
    /// </summary>
    public bool IsNearElevator { get; private set; }

    /// <summary>
    /// Indicates whether this room is positioned near a staircase.
    /// Used as the final tiebreaker in the room assignment algorithm.
    /// </summary>
    public bool IsNearStaircase { get; private set; }

    /// <summary>
    /// Timestamp of the last time the room status was changed to Clean.
    /// The Room Assignment Algorithm sorts candidate rooms by this value
    /// ascending to ensure even rotation — rooms clean the longest go first.
    /// Null means the room has never been cleaned (newly registered).
    /// </summary>
    public DateTime? LastCleanedAt { get; private set; }

    public DateTime CreatedAt { get; private set; }
    public DateTime UpdatedAt { get; private set; }

    /// <summary>
    /// EF Core Optimistic Concurrency token. The [Timestamp] attribute maps this
    /// to a PostgreSQL xmin column (or rowversion-equivalent). EF Core automatically
    /// includes this in every UPDATE's WHERE clause and throws DbUpdateConcurrencyException
    /// if the value no longer matches — our database-level double-booking guard.
    /// </summary>
    public byte[] RowVersion { get; private set; } = null!;

    // Navigation property — EF Core lazy loading boundary
    private readonly List<Booking> _bookings = [];
    public IReadOnlyCollection<Booking> Bookings => _bookings.AsReadOnly();

    // ── EF Core required parameterless constructor ─────────────────────────────
    private Room() { }

    // ── Factory ──────────────────────────────────────────────────────────────

    public static Room Create(
        RoomNumber roomNumber,
        RoomType type,
        Money nightlyRate,
        bool isNearElevator = false,
        bool isNearStaircase = false)
    {
        var room = new Room
        {
            Id = Guid.NewGuid(),
            RoomNumber = roomNumber,
            Type = type,
            Status = RoomStatus.Clean,   // All new rooms start clean and available
            NightlyRate = nightlyRate,
            Floor = roomNumber.Floor,
            IsNearElevator = isNearElevator,
            IsNearStaircase = isNearStaircase,
            LastCleanedAt = DateTime.UtcNow,
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow
        };

        return room;
    }

    // ── State Transition Methods ──────────────────────────────────────────────

    /// <summary>
    /// Transition: Available/Clean → PendingPayment.
    /// Called immediately when a booking is created; room is held while payment completes.
    /// A Redis TTL is set concurrently — if payment times out, the room reverts.
    /// </summary>
    public void HoldForPayment()
    {
        if (Status is not (RoomStatus.Available or RoomStatus.Clean))
            throw new InvalidOperationException(
                $"Room {RoomNumber} cannot be held — current status is {Status}.");

        Status = RoomStatus.PendingPayment;
        UpdatedAt = DateTime.UtcNow;

        RaiseDomainEvent(new RoomStatusChangedEvent(Id, RoomNumber.Value, RoomStatus.PendingPayment));
    }

    /// <summary>
    /// Transition: PendingPayment → Available.
    /// Called by the BackgroundService when the 15-minute payment Redis TTL expires.
    /// </summary>
    public void ReleaseFromPaymentHold()
    {
        if (Status != RoomStatus.PendingPayment)
            throw new InvalidOperationException(
                $"Room {RoomNumber} is not in PendingPayment state.");

        Status = RoomStatus.Available;
        UpdatedAt = DateTime.UtcNow;

        RaiseDomainEvent(new RoomStatusChangedEvent(Id, RoomNumber.Value, RoomStatus.Available));
    }

    /// <summary>
    /// Transition: PendingPayment → Occupied.
    /// Called after payment confirmation during check-in.
    /// </summary>
    public void CheckIn()
    {
        if (Status != RoomStatus.PendingPayment)
            throw new InvalidOperationException(
                $"Room {RoomNumber} cannot be checked in — payment not confirmed. Status: {Status}.");

        Status = RoomStatus.Occupied;
        UpdatedAt = DateTime.UtcNow;

        RaiseDomainEvent(new RoomStatusChangedEvent(Id, RoomNumber.Value, RoomStatus.Occupied));
    }

    /// <summary>
    /// Transition: Occupied → Dirty.
    /// Publishes RoomVacatedEvent so the Housekeeping module can react without
    /// Reception knowing anything about housekeeping internals.
    /// </summary>
    public void CheckOut()
    {
        if (Status != RoomStatus.Occupied)
            throw new InvalidOperationException(
                $"Room {RoomNumber} cannot be checked out — it is not occupied.");

        Status = RoomStatus.Dirty;
        UpdatedAt = DateTime.UtcNow;

        // This event crosses module boundaries via MediatR Publish.
        // Housekeeping subscribes to it; Reception does not know who the subscribers are.
        RaiseDomainEvent(new RoomVacatedEvent(Id, RoomNumber.Value, Floor));
        RaiseDomainEvent(new RoomStatusChangedEvent(Id, RoomNumber.Value, RoomStatus.Dirty));
    }

    /// <summary>
    /// Transition: Cleaning → Clean.
    /// Records the exact time cleaning finished for the assignment algorithm's
    /// "longest clean" sort criterion.
    /// </summary>
    public void MarkClean()
    {
        if (Status != RoomStatus.Cleaning)
            throw new InvalidOperationException(
                $"Room {RoomNumber} cannot be marked clean — it is not being cleaned. Status: {Status}.");

        Status = RoomStatus.Clean;
        LastCleanedAt = DateTime.UtcNow;
        UpdatedAt = DateTime.UtcNow;

        RaiseDomainEvent(new RoomStatusChangedEvent(Id, RoomNumber.Value, RoomStatus.Clean));
    }

    /// <summary>Transition: Dirty → Cleaning.</summary>
    public void StartCleaning()
    {
        if (Status != RoomStatus.Dirty)
            throw new InvalidOperationException(
                $"Room {RoomNumber} cannot start cleaning — it is not dirty. Status: {Status}.");

        Status = RoomStatus.Cleaning;
        UpdatedAt = DateTime.UtcNow;

        RaiseDomainEvent(new RoomStatusChangedEvent(Id, RoomNumber.Value, RoomStatus.Cleaning));
    }

    /// <summary>Transition: Any → UnderMaintenance.</summary>
    public void PlaceUnderMaintenance()
    {
        if (Status == RoomStatus.UnderMaintenance)
            return;

        Status = RoomStatus.UnderMaintenance;
        UpdatedAt = DateTime.UtcNow;

        RaiseDomainEvent(new RoomStatusChangedEvent(Id, RoomNumber.Value, RoomStatus.UnderMaintenance));
    }

    /// <summary>Transition: UnderMaintenance → Available.</summary>
    public void ReturnToService()
    {
        if (Status != RoomStatus.UnderMaintenance)
            throw new InvalidOperationException(
                $"Room {RoomNumber} is not under maintenance.");

        Status = RoomStatus.Available;
        UpdatedAt = DateTime.UtcNow;

        RaiseDomainEvent(new RoomStatusChangedEvent(Id, RoomNumber.Value, RoomStatus.Available));
    }
}
