// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Reception.Infrastructure.Persistence;

#nullable disable

namespace Reception.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ReceptionDbContext))]
    [Migration("20260607114556_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reception")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Reception.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PreferredFloor")
                        .HasColumnType("integer");

                    b.Property<string>("ProximityPreference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RequestedRoomType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GuestId")
                        .HasDatabaseName("IX_Bookings_GuestId");

                    b.HasIndex("RoomId", "Status")
                        .HasDatabaseName("IX_Bookings_RoomId_Status");

                    b.ToTable("Bookings", "reception");
                });

            modelBuilder.Entity("Reception.Domain.Entities.Guest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("MaskedCardLast4")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_Guests_Email");

                    b.ToTable("Guests", "reception");
                });

            modelBuilder.Entity("Reception.Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<bool>("IsNearElevator")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNearStaircase")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastCleanedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("RowVersion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LastCleanedAt")
                        .HasDatabaseName("IX_Rooms_LastCleanedAt");

                    b.HasIndex("Type", "Status")
                        .HasDatabaseName("IX_Rooms_Type_Status");

                    b.ToTable("Rooms", "reception");
                });

            modelBuilder.Entity("Reception.Domain.Entities.Booking", b =>
                {
                    b.HasOne("Reception.Domain.Entities.Guest", "Guest")
                        .WithMany("Bookings")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reception.Domain.Entities.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Reception.Domain.ValueObjects.Money", "ExtraFees", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("ExtraFees_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("ExtraFees_Currency")
                                .IsFixedLength();

                            b1.HasKey("BookingId");

                            b1.ToTable("Bookings", "reception");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsOne("Reception.Domain.ValueObjects.Money", "RoomCharge", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("RoomCharge_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("RoomCharge_Currency")
                                .IsFixedLength();

                            b1.HasKey("BookingId");

                            b1.ToTable("Bookings", "reception");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsOne("Reception.Domain.ValueObjects.Money", "RoomServiceCharges", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("RoomServiceCharges_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("RoomServiceCharges_Currency")
                                .IsFixedLength();

                            b1.HasKey("BookingId");

                            b1.ToTable("Bookings", "reception");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsOne("Reception.Domain.ValueObjects.Money", "TotalBill", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("TotalBill_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("TotalBill_Currency")
                                .IsFixedLength();

                            b1.HasKey("BookingId");

                            b1.ToTable("Bookings", "reception");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsMany("Reception.Domain.Entities.ExtraFeeLineItem", "ExtraFeeLineItems", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("AddedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("Id");

                            b1.HasIndex("BookingId");

                            b1.ToTable("BookingExtraFees", "reception");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");

                            b1.OwnsOne("Reception.Domain.ValueObjects.Money", "Amount", b2 =>
                                {
                                    b2.Property<int>("ExtraFeeLineItemId")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("Amount_Value");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character(3)")
                                        .HasColumnName("Amount_Currency")
                                        .IsFixedLength();

                                    b2.HasKey("ExtraFeeLineItemId");

                                    b2.ToTable("BookingExtraFees", "reception");

                                    b2.WithOwner()
                                        .HasForeignKey("ExtraFeeLineItemId");
                                });

                            b1.Navigation("Amount")
                                .IsRequired();
                        });

                    b.OwnsOne("Reception.Domain.ValueObjects.DateRange", "StayPeriod", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("CheckIn")
                                .HasColumnType("date")
                                .HasColumnName("CheckIn");

                            b1.Property<DateOnly>("CheckOut")
                                .HasColumnType("date")
                                .HasColumnName("CheckOut");

                            b1.HasKey("BookingId");

                            b1.ToTable("Bookings", "reception");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.Navigation("ExtraFeeLineItems");

                    b.Navigation("ExtraFees")
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("Room");

                    b.Navigation("RoomCharge")
                        .IsRequired();

                    b.Navigation("RoomServiceCharges")
                        .IsRequired();

                    b.Navigation("StayPeriod")
                        .IsRequired();

                    b.Navigation("TotalBill");
                });

            modelBuilder.Entity("Reception.Domain.Entities.Guest", b =>
                {
                    b.OwnsOne("Reception.Domain.ValueObjects.GuestName", "Name", b1 =>
                        {
                            b1.Property<Guid>("GuestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("LastName");

                            b1.HasKey("GuestId");

                            b1.ToTable("Guests", "reception");

                            b1.WithOwner()
                                .HasForeignKey("GuestId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Reception.Domain.Entities.Room", b =>
                {
                    b.OwnsOne("Reception.Domain.ValueObjects.Money", "NightlyRate", b1 =>
                        {
                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("NightlyRate_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("NightlyRate_Currency")
                                .IsFixedLength();

                            b1.HasKey("RoomId");

                            b1.ToTable("Rooms", "reception");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.OwnsOne("Reception.Domain.ValueObjects.RoomNumber", "RoomNumber", b1 =>
                        {
                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Floor")
                                .HasColumnType("integer")
                                .HasColumnName("RoomNumber_Floor");

                            b1.Property<int>("Unit")
                                .HasColumnType("integer")
                                .HasColumnName("RoomNumber_Unit");

                            b1.HasKey("RoomId");

                            b1.HasIndex("Floor", "Unit")
                                .IsUnique()
                                .HasDatabaseName("UQ_Rooms_RoomNumber");

                            b1.ToTable("Rooms", "reception");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.Navigation("NightlyRate")
                        .IsRequired();

                    b.Navigation("RoomNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("Reception.Domain.Entities.Guest", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Reception.Domain.Entities.Room", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
